FROM openjdk:8-jdk-alpine
COPY *.java /src/
RUN mkdir /app \
    && ls /src \
    && javac /src/PrintJdkInfo.java -d /app
CMD ["sh", "-c", \
     "java -version \
      && java -cp /app PrintJdkInfo"]